services:
    vllm-openai:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./models:/models
        environment:
            - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
            - NCCL_P2P_DISABLE=1
            - NCCL_IB_DISABLE=1
        ports:
            - 8000:8000
        ipc: host
        image: vllm/vllm-openai:latest
        command: --model Qwen/Qwen3-4B-Thinking-2507 --served-model-name local-qwen-thinking --gpu-memory-utilization 0.9 --enforce-eager --max-model-len 8192 --enable-auto-tool-choice --tool-call-parser hermes --reasoning-parser qwen3
